In [124]:
f = open("function.txt", "r")
function = f.read()

In [125]:
print(function)

5.22110329205413*T**9 + 106.21289553219*T**8*x + 22.8551081490528*T**8*y + 50.1309459085043*T**8*z - 54.7918530673146*T**8 + 689.024003490052*T**7*x**2 + 527.665149219633*T**7*x*y + 646.455283512912*T**7*x*z - 755.815278949024*T**7*x - 16.8936841211618*T**7*y**2 + 226.430205570206*T**7*y*z - 233.711032877291*T**7*y + 148.983017860753*T**7*z**2 - 355.965423157713*T**7*z + 199.999553536674*T**7 + 2086.10484154652*T**6*x**3 + 3571.35565532198*T**6*x**2*y + 2803.71165098843*T**6*x**2*z - 3757.36266270156*T**6*x**2 + 109.570674709273*T**6*x*y**2 + 3058.82836321173*T**6*x*y*z - 3180.21720095914*T**6*x*y + 1252.41396039173*T**6*x*z**2 - 3480.14021657994*T**6*x*z + 2093.4611244991*T**6*x - 105.361742986718*T**6*y**3 - 29.1225406540392*T**6*y**2*z + 0.36963502134347*T**6*y**2 + 575.562006166451*T**6*y*z**2 - 1363.95553180778*T**6*y*z + 694.663593370085*T**6*y + 191.155732136835*T**6*z**3 - 788.311888094903*T**6*z**2 + 968.874387453547*T**6*z - 371.125810449074*T**6 + 3098.0074696755*T**5*x**4 +

In [126]:
var_to_check = ['T', 'x', 'y', 'z']
check = ['T']
power = ''
for i in range(2,10):
    check.append('T**'+str(i))

print(check)

['T', 'T**2', 'T**3', 'T**4', 'T**5', 'T**6', 'T**7', 'T**8', 'T**9']


In [127]:
count = function.count('T')
print(count)

495


In [128]:
count = 0
for word in function.split():
    count += 1
    if 'T**3' in word:
        print(word)

print('Number of terms is', count)

1784.29361048619*T**3*x**6
18236.0436415383*T**3*x**5*y
17414.3294483889*T**3*x**5*z
2092.88546662464*T**3*x**5
23353.799534661*T**3*x**4*y**2
45769.8234428421*T**3*x**4*y*z
47779.4671866349*T**3*x**4*y
27094.0115773836*T**3*x**4*z**2
11748.981394374*T**3*x**4*z
9952.35269452583*T**3*x**4
11508.8658228467*T**3*x**3*y**3
41583.2439366259*T**3*x**3*y**2*z
33154.0669813532*T**3*x**3*y**2
43621.7602041886*T**3*x**3*y*z**2
102666.498152669*T**3*x**3*y*z
46860.1387524616*T**3*x**3*y
6792.04257614413*T**3*x**3*z**3
13505.5312344144*T**3*x**3*z**2
10410.7627601324*T**3*x**3*z
10490.042421172*T**3*x**3
3554.09512471399*T**3*x**2*y**4
25240.4833472694*T**3*x**2*y**3*z
16504.2783777434*T**3*x**2*y**3
10216.3570591688*T**3*x**2*y**2*z**2
31460.5008400206*T**3*x**2*y**2*z
16738.3871797175*T**3*x**2*y**2
15124.091827484*T**3*x**2*y*z**3
71172.1142854533*T**3*x**2*y*z**2
79539.6772016561*T**3*x**2*y*z
21687.2853406168*T**3*x**2*y
5223.87508371556*T**3*x**2*z**4
7611.60286437377*T**3*x**2*z**3
10834.4

In [129]:
from sympy import symbols, init_printing
from sympy import *
import pandas as pd
from sympy.physics.quantum import TensorProduct
import numpy as np
import tensorflow as tf
import sympy

T, x, y, z = symbols('T x y z')

In [130]:
expr = sympify(function)

In [131]:
def extract_coefficients(expr, polys):
    result = {}
    for poly in polys:
        # if poly == 1:
        #     continue
        # else:
        #     # coef = float(expr.coeff(poly))
        coef = expr.coeff(poly) 
        result[poly] = coef
        expr = expr - poly*coef
    expr = expr.n()
    if isinstance(expr, (sympy.Float, sympy.Integer)):
        result[1] = float(expr)
        expr = sympy.S.Zero
    # if expr is not sympy.S.Zero:
    #     raise ValueError(expr)
    return tuple(result[p] for p in polys)

In [132]:
# extract_coefficients(expr, [T, T**2, T**3])
Xs_list = []
Ys_list = []
Ys_list_small = []
Ts = extract_coefficients(expr, [T, T**2, T**3, T**4, T**5, T**6, T**7, T**8, T**9])
for i in Ts:
    Xs = extract_coefficients(i, [x, x**2, x**3, x**4, x**5, x**6, x**7, x**8, x**9, x**10])
    Xs_list.append(Xs)
    Ys_list_small = []
    for j in Xs:
        Ys = extract_coefficients(j, [y, y**2, y**3, y**4, y**5, y**6, y**7, y**8, y**9, y**10])
        # for k in Ys:
        #    Zs = extract_coefficients(j, [z, z**2, z**3, z**4, z**5, z**6, z**7, z**8, z**9, z**10])
        Ys_list_small.append(Ys)
    Ys_list.append(Ys_list_small)
    # print(Xs)

In [133]:
# def (matrix, expr, var_list, nest)
#     f = function
#     var = var_list[0]
#     First = extract_coefficients(expr, [var, var**2, var**3, var**4, var**5, var**6, var**7, var**8, var**9])
#     Func_int = First
#         for i in range(nest):
#             inner_func(Func_int, )
#     def inner_func(Func_int, ):
#             for j in range(len(Func_int)):
#                 Func_int2 = extract_coefficients(Func_int[i], [x, x**2, x**3, x**4, x**5, x**6, x**7, x**8, x**9, x**10])    
#                 if i != nest:
#                     inner_func(Func_int2)
#                 else:
#                     for l in range(len(Zs)):
#                         matrix[i][j][k][l] = Zs[l]


#         for j in range(len(Xs)):
#             Ys = extract_coefficients(Xs[j], [y, y**2, y**3, y**4, y**5, y**6, y**7, y**8, y**9, y**10])
#             for k in range(len(Ys)):
#                 Zs = extract_coefficients(Ys[k], [z, z**2, z**3, z**4, z**5, z**6, z**7, z**8, z**9, z**10])
#                 for l in range(len(Zs)):
#                     matrix[i][j][k][l] = Zs[l]

In [134]:
# extract_coefficients(expr, [T, T**2, T**3])
matrix = np.zeros([10,10,10,10])
print(matrix.shape)

Ts = extract_coefficients(expr, [T, T**2, T**3, T**4, T**5, T**6, T**7, T**8, T**9, T**10])
for i in range(len(Ts)):
    Xs = extract_coefficients(Ts[i], [x, x**2, x**3, x**4, x**5, x**6, x**7, x**8, x**9, x**10])
    for j in range(len(Xs)):
        Ys = extract_coefficients(Xs[j], [y, y**2, y**3, y**4, y**5, y**6, y**7, y**8, y**9, y**10])
        for k in range(len(Ys)):
            Zs = extract_coefficients(Ys[k], [z, z**2, z**3, z**4, z**5, z**6, z**7, z**8, z**9, z**10])
            for l in range(len(Zs)):
                matrix[i][j][k][l] = Zs[l]

print(matrix[0])

(10, 10, 10, 10)
[[[-3.22741833e+03  8.48730354e+03 -4.06781577e+03 -8.93442705e+03
    9.61736587e+03 -2.15536873e+03  0.00000000e+00  0.00000000e+00
    0.00000000e+00  0.00000000e+00]
  [ 1.16393560e+03  7.99043498e+03 -1.95879799e+04  1.11571391e+04
   -7.02327687e+01  0.00000000e+00  0.00000000e+00  0.00000000e+00
    0.00000000e+00  0.00000000e+00]
  [ 7.24683546e+03 -1.10301433e+04  4.84248502e+02  4.44983191e+03
    0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
    0.00000000e+00  0.00000000e+00]
  [-3.84768793e+03  1.78602466e+02  1.07164516e+03  0.00000000e+00
    0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
    0.00000000e+00  0.00000000e+00]
  [-3.01105686e+03  9.93492520e+02  0.00000000e+00  0.00000000e+00
    0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
    0.00000000e+00  0.00000000e+00]
  [ 1.38409684e+02  0.00000000e+00  0.00000000e+00  0.00000000e+00
    0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00

In [135]:
print(matrix[0][0:3, 0:3, 0:3].shape)
tensor2 = matrix[0]

(3, 3, 3)


In [136]:
# type(0:2)

In [137]:
order = 2
indexing = np.asarray(list(range(0, order+1)))
print(matrix[0:order+1, 0:order+1, 0:order+1, 0:order+1].shape)

(3, 3, 3, 3)


In [138]:
# from pycalphad import model
# T, x, y, z = symbols('T x y z')
# comps = [x, y, z]
# return_dict = _Muggianu_correction_dict(comps)
# print(return_dict)

# # for i in list(return_dict.values()):
# #     add += (x*y*z)*i
# # print(simplify(expand(add)))

# add = x*y*z*(x.subs(return_dict) + y.subs(return_dict) + z.subs(return_dict))
# # add = x*y*z*(return_dict[x] + return_dict[y] + return_dict[z])
# print(simplify(expand(add)))

In [139]:
T, x, y, z = symbols('T x y z')
c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20, c21, c22, c23, c24, c25, c26, c27, c28, c29, c30, c31, c32, c33, c34, c35, c36, c37, c38, c39, c40,c41 = symbols('c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20, c21, c22, c23, c24, c25, c26, c27, c28, c29, c30, c31, c32, c33, c34, c35, c36, c37, c38, c39, c40,c41')

f = c1*x*y + c2*x*y*(x-y) + c3*x*y*(x-y)**2 + c4*y*z + c5*y*z*(y-z) + c6*y*z*(y-z)**2 + c7*x*z + c8*x*z*(x-z) + c9*x*z*(x-z)**2 + c10*x*y*z
#  + c11*x*y*z(2*x/3 - y/3 - z/3 + 1/3) + c12*x*y*z(2*x/3 - y/3 - z/3 + 1/3)**2 + c13*x*y*z(2*x/3 - y/3 - z/3 + 1/3)**3
# f += 
f = simplify(expand(f))
print(f)

c1*x*y + c10*x*y*z + c2*x**2*y - c2*x*y**2 + c3*x**3*y - 2*c3*x**2*y**2 + c3*x*y**3 + c4*y*z + c5*y**2*z - c5*y*z**2 + c6*y**3*z - 2*c6*y**2*z**2 + c6*y*z**3 + c7*x*z + c8*x**2*z - c8*x*z**2 + c9*x**3*z - 2*c9*x**2*z**2 + c9*x*z**3


In [140]:
# # compare = Array([10,10,10])
# Xs_list = []
# Ys_list = []
# compare = np.zeros([10,10,10])
# Xs = extract_coefficients(f, [x, x**2, x**3, x**4, x**5, x**6, x**7, x**8, x**9, x**10])
# for i in range(len(Xs)):
#     Ys = extract_coefficients(Xs[i], [y, y**2, y**3, y**4, y**5, y**6, y**7, y**8, y**9, y**10])
#     for j in range(len(Ys)):
#         Zs = extract_coefficients(Ys[j], [z, z**2, z**3, z**4, z**5, z**6, z**7, z**8, z**9, z**10])
#         for k in range(len(Zs)):
#             matrix[i][j][k] = Zs[k]

In [141]:
# assert_list = [c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20, c21, c22, c23, c24, c25, c26, c27, c28, c29, c30, c31, c32, c33, c34, c35, c36, c37, c38, c39, c40, c41]
# for i in assert_list:
#     assert i.is_constant()

In [142]:
# compare = Array([10,10,10])
Xs_list = []
Ys_list = []
Zs_list = []
compare = MutableDenseNDimArray([10,10,10])
print('f', f)
Xs = extract_coefficients(expand(f*x), [x, x**2, x**3, x**4, x**5, x**6, x**7, x**8, x**9, x**10])
# print('Xs',Xs)
for i in range(len(Xs)):
    Ys = extract_coefficients(expand(Xs[i]*y), [y, y**2, y**3, y**4, y**5, y**6, y**7, y**8, y**9, y**10])
    # print('Ys', Ys)
    Zs_list = []
    for j in range(len(Ys)):
        Zs = extract_coefficients(expand(Ys[j]*z), [z, z**2, z**3, z**4, z**5, z**6, z**7, z**8, z**9, z**10])
        # print('Zs', Zs)
        Zs_list.append(list(Zs))
    Ys_list.append(Zs_list)
Xs_list.append(Ys_list)

        # for k in range(len(Zs)):
            
        #     print(Zs[k])
        #     matrix[i][j][k] = Zs[k]
print('Final', Xs_list)



f c1*x*y + c10*x*y*z + c2*x**2*y - c2*x*y**2 + c3*x**3*y - 2*c3*x**2*y**2 + c3*x*y**3 + c4*y*z + c5*y**2*z - c5*y*z**2 + c6*y**3*z - 2*c6*y**2*z**2 + c6*y*z**3 + c7*x*z + c8*x**2*z - c8*x*z**2 + c9*x**3*z - 2*c9*x**2*z**2 + c9*x*z**3
Final [[[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, c4, -c5, c6, 0, 0, 0, 0, 0, 0], [0, c5, -2*c6, 0, 0, 0, 0, 0, 0, 0], [0, c6, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[0, c7, -c8, c9, 0, 0, 0, 0, 0, 0], [c1, c10, 0, 0, 0, 0, 0, 0, 0, 0], [-c2, 0, 0, 0, 0, 0, 0, 0, 0, 0], [c3, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[0, c8, -2*c9, 0, 0, 0, 0, 0, 0, 0], [c2, 0, 0, 0, 0, 0, 0, 0, 0, 0], [-2*c3, 0, 0, 0, 0, 0, 

In [143]:
# Xs_list
# sympy.Array(Xs_list).free_symbols
sympy.Array(Xs_list)

[[[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, c4, -c5, c6, 0, 0, 0, 0, 0, 0], [0, c5, -2*c6, 0, 0, 0, 0, 0, 0, 0], [0, c6, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[0, c7, -c8, c9, 0, 0, 0, 0, 0, 0], [c1, c10, 0, 0, 0, 0, 0, 0, 0, 0], [-c2, 0, 0, 0, 0, 0, 0, 0, 0, 0], [c3, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[0, c8, -2*c9, 0, 0, 0, 0, 0, 0, 0], [c2, 0, 0, 0, 0, 0, 0, 0, 0, 0], [-2*c3, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[

In [144]:
# from sympy.abc import c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16
from sympy.utilities.lambdify import implemented_function
from sympy import lambdify

parameter_unkowns = c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16

f = implemented_function('f', lambda parameter_unknows: tensor1)

lam_f = lambdify(parameter_unkowns, f(parameter_unkowns))

print(lam_f)



# lam_f(4)

<function _lambdifygenerated at 0x000001F149062830>


In [145]:
pprint(tensor1)

                  [[[[0 0 0 ... 0 0 0]                 
                   [0 c4 -c5 ... 0 0 0]                
                  [0 c5 -2*c6 ... 0 0 0]               
                            ...                        
                     [0 0 0 ... 0 0 0]                 
                     [0 0 0 ... 0 0 0]                 
                    [0 0 0 ... 0 0 0]]                 
                                                       
                  [[0 c7 -c8 ... 0 0 0]                
                   [c1 c10 0 ... 0 0 0]                
                    [-c2 0 0 ... 0 0 0]                
                            ...                        
                     [0 0 0 ... 0 0 0]                 
                     [0 0 0 ... 0 0 0]                 
                    [0 0 0 ... 0 0 0]]                 
                                                       
                 [[0 c8 -2*c9 ... 0 0 0]               
                    [c2 0 0 ... 0 0 0]          

In [146]:
# initial = matrix[0][0:4, 0:4, 0:4]
# result_to_get = tensor_to_fit[0]
C_tensor = tensor1 #symbolic
ML_tensor = tensor2 #numerical
print(tensor1.shape, tensor2.shape)
tensor_RK = np.asarray(C_tensor).astype(object)
tensor_ML = np.asarray(ML_tensor)
# tensor1 = tf.convert_to_tensor(tensor1).astype('char')
# initial_inv = tf.linalg.pinv(initial.astype('float32'))

# print(type(initial))

transformation = tensor_RK*np.linalg.pinv(tensor_ML) #symbolic*numerical = symbolic
pprint(transformation.shape)
# transformation = tf.multiply(tensor1, tf.linalg.pinv(tensor2.astype('float32')))
# # print(transformation.shape)

# transformation_tensor = tf.multiply(tensor1, tf.lin)

(3, 10, 10, 10) (10, 10, 10)
(3, 10, 10, 10)


In [147]:
# fit = x*y*(c1+c2*T+c4*T**2)
# fit += x*y*(x-y)*(c5+c6*T)
# fit += x*y*(x-y)**2*(c7)
# fit += x*z*(c8+c9*T)
# fit += x*z*(x-z)*(c10)
# fit += x*z*(x-z)**2*(c11)
# fit += z*y*(c12)
# fit += z*x*(z-x)*(c13)
# fit += z*x*(z-x)**2*(c14)
# fit += x*z*x*(c15+c16*T)

#no temperature dependence
fit = x*y*(c1+c2+c3+c4)
fit += x*y*(x-y)*(c5+c6)
fit += x*y*(x-y)**2*(c7)
fit += x*z*(c8+c9)
fit += x*z*(x-z)*(c10)
fit += x*z*(x-z)**2*(c11)
fit += z*y*(c12)
fit += z*x*(z-x)*(c13)
fit += z*x*(z-x)**2*(c14)
fit += x*z*x*(c15+c16)


# compare = Array([10,10,10])
Xs_list_fit = []
Ys_list = []
Zs_list = []
compare = MutableDenseNDimArray([10,10,10])
print('f', f)
Xs = extract_coefficients(expand(fit*x), [x, x**2, x**3, x**4])
# print('Xs',Xs)
for i in range(len(Xs)):
    Ys = extract_coefficients(expand(Xs[i]*y), [y, y**2, y**3, y**4])
    # print('Ys', Ys)
    Zs_list = []
    for j in range(len(Ys)):
        Zs = extract_coefficients(expand(Ys[j]*z), [z, z**2, z**3, z**4])
        # print('Zs', Zs)
        Zs_list.append(list(Zs))
    Ys_list.append(Zs_list)
Xs_list_fit.append(Ys_list)

        # for k in range(len(Zs)):
            
        #     print(Zs[k])
        #     matrix[i][j][k] = Zs[k]
print('Final', Xs_list_fit)




f f
Final [[[[0, 0, 0, 0], [0, c12, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, c8 + c9, -c10 + c13, c11 + c14], [c1 + c2 + c3 + c4, 0, 0, 0], [-c5 - c6, 0, 0, 0], [c7, 0, 0, 0]], [[0, c10 - c13 + c15 + c16, -2*c11 - 2*c14, 0], [c5 + c6, 0, 0, 0], [-2*c7, 0, 0, 0], [0, 0, 0, 0]], [[0, c11 + c14, 0, 0], [c7, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]]]


In [148]:
# Xs_list
# sympy.Array(Xs_list).free_symbols
tensor_to_fit = sympy.Array(Xs_list_fit)

In [149]:
X_fit = np.asarray([-7.58028093e+04,  6.55754782e+02, -9.51843761e+01,  4.00848967e-02,
        1.59310513e+03,  3.67081008e+00, -8.57196248e+03, -1.52070015e+05,
       -1.09017962e+01,  7.80423356e+05,  1.80147451e+08, -6.74402610e+03,
        8.70741052e+05, -1.80147518e+08,  1.66867702e+05,  2.04970791e+01,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00])

print(X_fit.shape)

parameters_to_fit = [c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16]

for i in range(0,16):
    # print(parameters_to_fit[i])
    tensor_to_fit = tensor_to_fit.subs(parameters_to_fit[i], list(X_fit)[i])
    # print(list(X_fit)[i])

pprint(tensor_to_fit)

(41,)
⎡⎡⎡0      0       0  0⎤  ⎡        0          -152080.9167962  90317.696  -67.0
⎢⎢⎢                   ⎥  ⎢                                                    
⎢⎢⎢0  -6744.0261  0  0⎥  ⎢-75242.1988092033         0             0        0  
⎢⎢⎢                   ⎥  ⎢                                                    
⎢⎢⎢0      0       0  0⎥  ⎢ -1596.77594008           0             0        0  
⎢⎢⎢                   ⎥  ⎢                                                    
⎣⎣⎣0      0       0  0⎦  ⎣   -8571.96248            0             0        0  

⎤  ⎡      0        76570.5030791  134.0  0⎤  ⎡     0       -67.0  0  0⎤⎤⎤
⎥  ⎢                                      ⎥  ⎢                        ⎥⎥⎥
⎥  ⎢1596.77594008        0          0    0⎥  ⎢-8571.96248    0    0  0⎥⎥⎥
⎥  ⎢                                      ⎥  ⎢                        ⎥⎥⎥
⎥  ⎢ 17143.92496         0          0    0⎥  ⎢     0         0    0  0⎥⎥⎥
⎥  ⎢                                      ⎥  ⎢                        

In [150]:
print(tensor_to_fit[0].shape, matrix[0][0:4, 0:4, 0:4].shape)

initial = matrix[0][0:4, 0:4, 0:4]
result_to_get = tensor_to_fit[0]
result_to_get = np.asarray(result_to_get).astype('float32')
result_to_get = tf.convert_to_tensor(result_to_get)
initial_inv = tf.linalg.pinv(initial.astype('float32'))

print(type(initial))

transformation = tf.multiply(result_to_get, initial_inv)
print(transformation.shape)

(4, 4, 4) (4, 4, 4)
<class 'numpy.ndarray'>
(4, 4, 4)


In [151]:
X = Poly(f, x)
X_coeffs = X.coeffs()
print('X', X_coeffs)   

Y_coeffs = []
for i in X_coeffs:
    Y = Poly(i, y)
    Y_coeffs.append(Y.coeffs())
print('Y', Y_coeffs)

Final_matrix = []

for i in Y_coeffs:
    Z_coeffs = []
    for j in i:
        Z = Poly(j, z)
        Z_coeffs.append(Z.coeffs())
    Final_matrix.append(Z_coeffs)


print('Final Matrix', Final_matrix)

print(len(X_coeffs), len(Y_coeffs), len(Y_coeffs[0]), len(Z_coeffs))

PolynomialError: expression must be of type Expr

In [ ]:
Zs.as_coefficients_dict()[S.One]

AttributeError: 'tuple' object has no attribute 'as_coefficients_dict'

In [ ]:
from pycalphad import Database
dbf = Database('Mg_Si_Zn-mixingonly.tdb')
comps = ['MG', 'SI', 'ZN', 'VA']
def _Muggianu_correction_dict(comps): #pylint: disable=C0103
        """
        Replace y_i -> y_i + (1 - sum(y involved in parameter)) / m,
        where m is the arity of the interaction parameter.
        Returns a dict converting the list of Symbols (comps) to this.
        m is assumed equal to the length of comps.
        When incorporating binary, ternary or n-ary interaction parameters
        into systems with more than n components, the sum of site fractions
        involved in the interaction parameter may no longer be unity. This
        breaks the symmetry of the parameter. The solution suggested by
        Muggianu, 1975, is to renormalize the site fractions by replacing them
        with a term that will sum to unity even in higher-order systems.
        There are other solutions that involve retaining the asymmetry for
        physical reasons, but this solution works well for components that
        are physically similar.
        This procedure is based on an analysis by Hillert, 1980,
        published in the Calphad journal.
        """
        arity = len(comps)
        return_dict = {}
        correction_term = (S.One - Add(*comps)) / arity
        for comp in comps:
            return_dict[comp] = comp + correction_term
        return return_dict

return_dict = _Muggianu_correction_dict(comps)

SympifyError: SympifyError: 'MG'

In [ ]:
test_list = []
for i in range(3):
    for j in range(3):
        test_list.append(x**i*y**j)

print(test_list)

[1, y, y**2, x, x*y, x*y**2, x**2, x**2*y, x**2*y**2]


In [ ]:
Xs_list[0][0]

-202.201900604718*y**7 + 138.409683576739*y**6*z - 539.251190264315*y**6 + 993.492520369481*y**5*z**2 - 3011.05686020635*y**5*z + 1083.33920641707*y**5 + 1071.64516084691*y**4*z**3 + 178.602465948678*y**4*z**2 - 3847.68793400637*y**4*z + 1838.8442245673*y**4 + 4449.83191281374*y**3*z**4 + 484.248502041328*y**3*z**3 - 11030.1433183376*y**3*z**2 + 7246.83545874285*y**3*z - 1005.03048151605*y**3 - 70.2327687366633*y**2*z**5 + 11157.1391054799*y**2*z**4 - 19587.9799260731*y**2*z**3 + 7990.43498337635*y**2*z**2 + 1163.93560116574*y**2*z - 603.893332898698*y**2 - 2155.36872964672*y*z**6 + 9617.36586667336*y*z**5 - 8934.42704671868*y*z**4 - 4067.81577258997*y*z**3 + 8487.30353720832*y*z**2 - 3227.41833120724*y*z + 367.969953242459*y - 969.072523686815*z**7 + 2132.21050197004*z**6 + 864.689302178735*z**5 - 5349.8432971545*z**4 + 5029.1578980949*z**3 - 1666.89077192751*z**2 + 167.64470426173*z - 11.5436096489429

In [ ]:
from sympy import factor,pprint


# pprint(expr)

# Factor function
factored_Xs_list_1 = factor(Ys_list[0][0][0])
# factored_expr = factor(expr)
print(factored_Xs_list_1)

-9617.36586667336*(0.224112169540687*z**6 - 1.0*z**5 + 0.928988994551903*z**4 + 0.422965688212611*z**3 - 0.882497729094305*z**2 + 0.335582359655368*z - 0.0382609914547984)


In [ ]:
expr.as_poly(T).all_coeffs

TypeError: object of type 'method' has no len()

In [ ]:
print(collect(Xs_list[0][0],y - z,evaluate=False)[y - z])

KeyError: y - z